
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:video_player/video_player.dart';

import '../../common/media/image_viewer_screen.dart';
import '../../common/media/pdf_viewer_screen.dart';
import '../utils/chat_reply_codec.dart';
import 'chat_audio_bubble.dart';

class ChatMessageBubble extends StatelessWidget {
  const ChatMessageBubble({
    super.key,
    required this.contextForNavigation,
    required this.rawText,
    required this.mediaUrl,
    required this.isMine,
    required this.showName,
    required this.senderLabel,
    required this.timeLabel,
    required this.edited,
    required this.reaction,
    required this.forwarded,
    this.delivered = false,
    this.seen = false,
    required this.deleteState,
    this.voiceDurationSeconds,
    this.voiceUnread = false,
    this.onVoicePlayed,
    this.replySender,
    this.replySnippet,
    this.mediaMimeType,
    this.messageKind = 'TEXT',
    this.maxWidth = 236,
    this.previewMode = false,
    this.previewMaxHeight,
  });

  final BuildContext contextForNavigation;
  final String rawText;
  final String mediaUrl;
  final bool isMine;
  final bool showName;
  final String senderLabel;
  final String timeLabel;
  final bool edited;
  final String? reaction;
  final bool forwarded;
  final bool delivered;
  final bool seen;
  final String deleteState;
  final int? voiceDurationSeconds;
  final bool voiceUnread;
  final VoidCallback? onVoicePlayed;
  final String? replySender;
  final String? replySnippet;
  final String? mediaMimeType;
  final String messageKind;
  final double maxWidth;
  final bool previewMode;
  final double? previewMaxHeight;

  bool _isImageByUrl(String v) =>
      RegExp(r'\.(jpg|jpeg|png|webp|gif|heic|heif)(\?|$)', caseSensitive: false)
          .hasMatch(v);

  bool _isVoiceByUrl(String v) =>
      RegExp(r'\.(m4a|aac|mp3|wav)(\?|$)', caseSensitive: false).hasMatch(v);

  bool _isVideoByUrl(String v) =>
      RegExp(r'\.(mp4|mov|m4v|webm)(\?|$)', caseSensitive: false).hasMatch(v);

  bool _isPdfByUrl(String v) =>
      RegExp(r'\.pdf(\?|$)', caseSensitive: false).hasMatch(v);

  bool _isImageByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'IMAGE' ||
        m.startsWith('image/') ||
        m.contains('jpeg') ||
        m.contains('jpg') ||
        m.contains('png') ||
        m.contains('webp') ||
        m.contains('gif') ||
        m.contains('heic') ||
        m.contains('heif');
  }

  bool _isVoiceByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'VOICE' ||
        m.startsWith('audio/') ||
        m.contains('mpeg') ||
        m.contains('mp4') ||
        m.contains('aac') ||
        m.contains('wav');
  }

  bool _isVideoByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'VIDEO' ||
        m.startsWith('video/') ||
        m.contains('mp4') ||
        m.contains('quicktime') ||
        m.contains('webm');
  }

  String _resolveMediaUrl(String raw) {
    final value = raw.trim();
    if (value.isEmpty) return '';

    final uri = Uri.tryParse(value);
    if (uri != null && uri.hasScheme) return value;

    const base = String.fromEnvironment('CM_API_BASE_URL');
    final normalizedBase = base.trim().replaceAll(RegExp(r'/+$'), '');
    if (normalizedBase.isEmpty) return value;

    final normalizedPath = value.startsWith('/') ? value : '/$value';
    return '$normalizedBase$normalizedPath';
  }

  String _displayFileName(String resolvedMediaUrl) {
    final parsed = Uri.tryParse(resolvedMediaUrl);
    if (parsed != null && parsed.pathSegments.isNotEmpty) {
      final last = Uri.decodeComponent(parsed.pathSegments.last.trim());
      if (last.isNotEmpty) return last;
    }
    final parts = resolvedMediaUrl.split('/');
    return parts.isEmpty ? 'File' : parts.last;
  }

  bool _looksLikeFileName(String value) {
    return RegExp(
      r'^[^\/]+\.(jpg|jpeg|png|webp|gif|heic|heif|mp4|mov|m4v|webm|m4a|aac|mp3|wav|pdf|doc|docx|xls|xlsx|ppt|pptx)$',
      caseSensitive: false,
    ).hasMatch(value.trim());
  }

  bool _shouldHideAutogeneratedMediaLabel({
    required String body,
    required String resolvedMediaUrl,
    required bool hasMedia,
    required String kind,
    required String mime,
  }) {
    if (!hasMedia) return false;

    final normalizedBody = body.trim();
    if (normalizedBody.isEmpty) return true;

    final lowerBody = normalizedBody.toLowerCase();
    if (lowerBody == '[image]' ||
        lowerBody == '[video]' ||
        lowerBody == '[voice]' ||
        lowerBody == '[file]') {
      return true;
    }

    final fileName = _displayFileName(resolvedMediaUrl).trim();
    final stem = fileName.contains('.')
        ? fileName.substring(0, fileName.lastIndexOf('.'))
        : fileName;

    final candidates = <String>{
      fileName,
      fileName.replaceAll('_', ' '),
      stem,
      stem.replaceAll('_', ' '),
    }..removeWhere((e) => e.trim().isEmpty);

    if (candidates.any((e) => e.trim().toLowerCase() == lowerBody)) {
      return true;
    }

    final upperKind = kind.trim().toUpperCase();
    final lowerMime = mime.trim().toLowerCase();
    final isMediaish = upperKind == 'IMAGE' ||
        upperKind == 'VIDEO' ||
        upperKind == 'VOICE' ||
        upperKind == 'FILE' ||
        lowerMime.startsWith('image/') ||
        lowerMime.startsWith('video/') ||
        lowerMime.startsWith('audio/') ||
        lowerMime.contains('quicktime') ||
        lowerMime.contains('mp4') ||
        lowerMime.contains('webm') ||
        lowerMime.contains('mpeg') ||
        lowerMime.contains('aac') ||
        lowerMime.contains('wav') ||
        lowerMime.contains('pdf') ||
        lowerMime.contains('officedocument') ||
        lowerMime.contains('msword') ||
        lowerMime.contains('excel') ||
        lowerMime.contains('spreadsheet') ||
        lowerMime.contains('presentation');

    return isMediaish && _looksLikeFileName(normalizedBody);
  }





  Widget _buildChecks() {
    if (!isMine) return const SizedBox.shrink();

    if (seen) {
      return Icon(
        Icons.done_all_rounded,
        size: 15,
        color: Colors.lightBlueAccent.shade100,
      );
    }

    if (delivered) {
      return Icon(
        Icons.done_all_rounded,
        size: 15,
        color: Colors.white.withValues(alpha: 0.78),
      );
    }

    return Icon(
      Icons.done_rounded,
      size: 15,
      color: Colors.white.withValues(alpha: 0.78),
    );
  }

  Future<void> _openAttachment(
    BuildContext context,
    String url,
    String label, {
    String kind = '',
    String mime = '',
  }) async {
    if (_isImageByUrl(url) || _isImageByMeta(kind, mime)) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => ImageViewerScreen(url: url, label: label),
        ),
      );
      return;
    }

    if (_isVideoByUrl(url) || _isVideoByMeta(kind, mime)) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => _InlineVideoViewerScreen(url: url),
        ),
      );
      return;
    }
    if (_isPdfByUrl(url) || mime.trim().toLowerCase().contains('pdf')) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => PdfViewerScreen(url: url, label: label),
        ),
      );
      return;
    }

    final uri = Uri.tryParse(url);
    if (uri == null) return;
    await launchUrl(uri, mode: LaunchMode.platformDefault);
  }

  @override
  Widget build(BuildContext context) {
    final deleteMode = deleteState.trim().toUpperCase();
    final isDeletedForEveryone = deleteMode == 'DELETED_FOR_EVERYONE';
    final isDeletedForMe = deleteMode == 'DELETED_FOR_ME';

    final parts = splitReplyRaw(rawText);
    final inlineReplyPrefix = parts.replyPrefix.trim();
    final body = parts.bodyText.trim();
    final resolvedMime = (mediaMimeType ?? '').trim();

    var resolvedReplySender = (replySender ?? '').trim();
    var resolvedReplySnippet = (replySnippet ?? '').trim();

    if (resolvedReplySender.isEmpty && inlineReplyPrefix.startsWith('↪ ')) {
      final afterArrow = inlineReplyPrefix.substring(2).trim();
      final colon = afterArrow.indexOf(':');
      if (colon != -1) {
        resolvedReplySender = afterArrow.substring(0, colon).trim();
        resolvedReplySnippet = afterArrow.substring(colon + 1).trim();
      } else {
        resolvedReplySnippet = afterArrow;
      }
      if (resolvedReplySnippet.endsWith('—')) {
        resolvedReplySnippet = resolvedReplySnippet
            .substring(0, resolvedReplySnippet.length - 1)
            .trimRight();
      }
    }
    final resolvedMediaUrl = _resolveMediaUrl(mediaUrl);
    final lowerUrl = resolvedMediaUrl.toLowerCase();
    final lowerBody = body.toLowerCase();
    final hasMedia = resolvedMediaUrl.isNotEmpty;

    final hideAutogeneratedMediaLabel = _shouldHideAutogeneratedMediaLabel(
      body: body,
      resolvedMediaUrl: resolvedMediaUrl,
      hasMedia: hasMedia,
      kind: messageKind,
      mime: resolvedMime,
    );

    final isImage =
        hasMedia &&
        (_isImageByUrl(lowerUrl) || _isImageByMeta(messageKind, resolvedMime));
    final isVoice =
        hasMedia &&
        (_isVoiceByUrl(lowerUrl) || _isVoiceByMeta(messageKind, resolvedMime));
    final isPdf =
        hasMedia &&
        (_isPdfByUrl(lowerUrl) || resolvedMime.toLowerCase().contains('pdf'));
    final isVideo =
        hasMedia &&
        (_isVideoByUrl(lowerUrl) || _isVideoByMeta(messageKind, resolvedMime));
    final isFileLike = hasMedia && !isImage && !isVoice && !isVideo;
    final displayFileName = _displayFileName(resolvedMediaUrl);

    final showRealUserCaption =
        body.isNotEmpty &&
        !hideAutogeneratedMediaLabel &&
        !_looksLikeFileName(body);

    if (isDeletedForMe) {
      return const SizedBox.shrink();
    }

    Widget bubble = ConstrainedBox(
      constraints: BoxConstraints(maxWidth: maxWidth),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: isMine
            ? CrossAxisAlignment.end
            : CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.fromLTRB(6, 3, 6, 3),
            decoration: BoxDecoration(
              color: isMine
                  ? Color.alphaBlend(
                      Theme.of(contextForNavigation).colorScheme.primary.withValues(
                        alpha: 0.26,
                      ),
                      Theme.of(contextForNavigation).colorScheme.surface,
                    )
                  : Theme.of(contextForNavigation).colorScheme.surfaceContainerHighest.withValues(
                      alpha: 0.55,
                    ),
              borderRadius: BorderRadius.only(
                topLeft: const Radius.circular(13),
                topRight: const Radius.circular(13),
                bottomLeft: Radius.circular(isMine ? 13 : 4),
                bottomRight: Radius.circular(isMine ? 4 : 13),
              ),
              border: Border.all(
                color: isMine
                    ? Theme.of(contextForNavigation).colorScheme.primary.withValues(
                        alpha: 0.24,
                      )
                    : Colors.white.withValues(alpha: 0.04),
              ),
              boxShadow: isMine
                  ? [
                      BoxShadow(
                        color: Theme.of(contextForNavigation).colorScheme.primary.withValues(
                          alpha: 0.18,
                        ),
                        blurRadius: 18,
                        spreadRadius: 0,
                        offset: const Offset(0, 2),
                      ),
                    ]
                  : null,
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (showName && !isMine) ...[
                  Text(
                    senderLabel,
                    style: TextStyle(
                      color: Colors.white.withValues(alpha: 0.78),
                      fontSize: 10.5,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 2),
                ],
                if (forwarded) ...[
                  Container(
                    margin: const EdgeInsets.only(bottom: 3),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(
                          Icons.forward_rounded,
                          size: 13,
                          color: Colors.white.withValues(alpha: 0.68),
                        ),
                        const SizedBox(width: 4),
                        Text(
                          'Forwarded',
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.68),
                            fontSize: 10.5,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
                if (resolvedReplySender.isNotEmpty ||
                    resolvedReplySnippet.isNotEmpty ||
                    inlineReplyPrefix.isNotEmpty) ...[
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.fromLTRB(6, 4, 6, 4),
                    margin: const EdgeInsets.only(bottom: 3),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.08),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(
                        color: Colors.white.withValues(alpha: 0.05),
                      ),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          resolvedReplySender.isEmpty
                              ? 'Reply'
                              : resolvedReplySender,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.w700,
                            fontSize: 11.5,
                          ),
                        ),
                        const SizedBox(height: 1),
                        Text(
                          resolvedReplySnippet.isEmpty
                              ? 'Message'
                              : resolvedReplySnippet,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.78),
                            fontSize: 11.5,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
                if (isDeletedForEveryone) ...[
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        Icons.block_rounded,
                        size: 16,
                        color: Colors.white.withValues(alpha: 0.78),
                      ),
                      const SizedBox(width: 7),
                      Text(
                        'This message was deleted',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.78),
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    ],
                  ),
                ] else if (isImage) ...[
                  GestureDetector(
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      resolvedMediaUrl,
                      body.isEmpty ? 'Image' : body,
                      kind: messageKind,
                      mime: resolvedMime,
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(14),
                      child: ConstrainedBox(
                        constraints: BoxConstraints(
                          minHeight: previewMode ? 132 : 96,
                          maxHeight: previewMode ? 132 : 260,
                        ),
                        child: Image.network(
                          resolvedMediaUrl,
                          width: double.infinity,
                          fit: BoxFit.cover,
                          errorBuilder: (context, error, stackTrace) => Container(
                            height: previewMode ? 132 : 180,
                            alignment: Alignment.center,
                            color: Colors.white.withValues(alpha: 0.06),
                            child: const Icon(
                              Icons.broken_image_outlined,
                              color: Colors.white70,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                  if (showRealUserCaption &&
                      !lowerBody.startsWith('[image]')) ...[
                    const SizedBox(height: 2),
                    _CollapsibleMessageText(
                      text: body,
                      previewMode: previewMode,
                    ),
                  ],
                ] else if (isVoice) ...[
                  ChatAudioBubble(
                    url: resolvedMediaUrl,
                    durationSeconds: voiceDurationSeconds,
                    isUnread: voiceUnread,
                    onPlayed: onVoicePlayed,
                  ),
                  if (showRealUserCaption &&
                      !lowerBody.startsWith('[voice]')) ...[
                    const SizedBox(height: 2),
                    _CollapsibleMessageText(
                      text: body,
                      previewMode: previewMode,
                    ),
                  ],
                ] else if (isVideo) ...[
                  _InlineVideoBubble(
                    url: resolvedMediaUrl,
                    previewMode: previewMode,
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      resolvedMediaUrl,
                      body.isEmpty ? 'Video' : body,
                      kind: messageKind,
                      mime: resolvedMime,
                    ),
                  ),
                  if (showRealUserCaption) ...[
                    const SizedBox(height: 3),
                    _CollapsibleMessageText(
                      text: body,
                      previewMode: previewMode,
                    ),
                  ],
                ] else if (isPdf || isFileLike) ...[
                  GestureDetector(
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      resolvedMediaUrl,
                      body.isEmpty ? 'File' : body,
                      kind: messageKind,
                      mime: resolvedMime,
                    ),
                    child: Container(
                      width: double.infinity,
                      padding: const EdgeInsets.fromLTRB(9, 9, 9, 9),
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(14),
                        border: Border.all(
                          color: Colors.white.withValues(alpha: 0.05),
                        ),
                      ),
                      child: Row(
                        children: [
                          Container(
                            width: 30,
                            height: 30,
                            decoration: BoxDecoration(
                              color: Colors.white.withValues(alpha: 0.10),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            alignment: Alignment.center,
                            child: Icon(
                              isPdf
                                  ? Icons.picture_as_pdf_rounded
                                  : Icons.insert_drive_file_rounded,
                              color: Colors.white,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              showRealUserCaption
                                  ? body
                                  : displayFileName,
                              maxLines: 2,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(color: Colors.white),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ] else if (showRealUserCaption) ...[
                    _CollapsibleMessageText(
                      text: body,
                      previewMode: previewMode,
                    ),                ],
                const SizedBox(height: 3),
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (edited)
                      Text(
                        'edited',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.55),
                          fontSize: 11,
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    if (edited) const SizedBox(width: 6),
                    Text(
                      timeLabel,
                      style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.62),
                        fontSize: 11,
                      ),
                    ),
                    if (isMine) const SizedBox(width: 6),
                    if (isMine) _buildChecks(),
                  ],
                ),
              ],
            ),
          ),
          if ((reaction ?? '').trim().isNotEmpty) ...[
            const SizedBox(height: 3),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(999),
                border: Border.all(color: Colors.white.withValues(alpha: 0.06)),
              ),
              child: Text(
                reaction!.trim(),
                style: const TextStyle(fontSize: 12),
              ),
            ),
          ],
        ],
      ),
    );

    if (!previewMode) {
      return bubble;
    }

    return ConstrainedBox(
      constraints: BoxConstraints(
        maxWidth: maxWidth,
        maxHeight: previewMaxHeight ?? 220,
      ),
      child: ClipRect(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          child: bubble,
        ),
      ),
    );
  }
}


class _CollapsibleMessageText extends StatefulWidget {
  const _CollapsibleMessageText({
    required this.text,
    required this.previewMode,
  });

  final String text;
  final bool previewMode;

  @override
  State<_CollapsibleMessageText> createState() => _CollapsibleMessageTextState();
}

class _CollapsibleMessageTextState extends State<_CollapsibleMessageText> {
  bool _expanded = false;

  @override
  Widget build(BuildContext context) {
    final collapsedMaxLines = widget.previewMode ? 5 : 8;
    final style = const TextStyle(color: Colors.white);

    return LayoutBuilder(
      builder: (context, constraints) {
        final span = TextSpan(text: widget.text, style: style);
        final painter = TextPainter(
          text: span,
          maxLines: collapsedMaxLines,
          textDirection: Directionality.of(context),
        )..layout(maxWidth: constraints.maxWidth);

        final exceeds = painter.didExceedMaxLines;

        return Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              widget.text,
              maxLines: _expanded ? null : collapsedMaxLines,
              overflow: _expanded ? TextOverflow.visible : TextOverflow.ellipsis,
              style: style,
            ),
            if (exceeds && !widget.previewMode) ...[
              const SizedBox(height: 3),
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: () => setState(() => _expanded = !_expanded),
                child: Text(
                  _expanded ? 'Read less' : 'Read more',
                  style: TextStyle(
                    color: Colors.white.withValues(alpha: 0.96),
                    fontSize: 11.5,
                    fontWeight: FontWeight.w700,
                    shadows: [
                      Shadow(
                        color: Colors.white.withValues(alpha: 0.20),
                        blurRadius: 10,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ],
        );
      },
    );
  }
}

class _InlineVideoBubble extends StatefulWidget {
  const _InlineVideoBubble({
    required this.url,
    required this.onTap,
    this.previewMode = false,
  });

  final String url;
  final VoidCallback onTap;
  final bool previewMode;

  @override
  State<_InlineVideoBubble> createState() => _InlineVideoBubbleState();
}

class _InlineVideoBubbleState extends State<_InlineVideoBubble> {
  VideoPlayerController? _controller;

  @override
  void initState() {
    super.initState();
    final uri = Uri.tryParse(widget.url);
    if (uri != null) {
      _controller = VideoPlayerController.networkUrl(uri)
        ..initialize().then((_) {
          if (mounted) setState(() {});
        }).catchError((_) {});
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = _controller;
    final ready = c != null && c.value.isInitialized;

    return GestureDetector(
      onTap: widget.onTap,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(14),
        child: Container(
          constraints: BoxConstraints(minHeight: widget.previewMode ? 132 : 96, maxHeight: widget.previewMode ? 132 : 220),
          width: double.infinity,
          color: Colors.white.withValues(alpha: 0.06),
          child: Stack(
            alignment: Alignment.center,
            children: [
              if (ready)
                AspectRatio(
                  aspectRatio: c.value.aspectRatio == 0 ? 16 / 9 : c.value.aspectRatio,
                  child: VideoPlayer(c),
                )
              else
                SizedBox(
                  height: widget.previewMode ? 132 : 180,
                  child: Center(
                    child: Icon(
                      Icons.videocam_rounded,
                      color: Colors.white70,
                      size: 40,
                    ),
                  ),
                ),
              Container(
                width: 52,
                height: 52,
                decoration: BoxDecoration(
                  color: Colors.black.withValues(alpha: 0.45),
                  shape: BoxShape.circle,
                ),
                alignment: Alignment.center,
                child: const Icon(
                  Icons.play_arrow_rounded,
                  color: Colors.white,
                  size: 32,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _InlineVideoViewerScreen extends StatefulWidget {
  const _InlineVideoViewerScreen({
    required this.url,
  });

  final String url;

  @override
  State<_InlineVideoViewerScreen> createState() => _InlineVideoViewerScreenState();
}

class _InlineVideoViewerScreenState extends State<_InlineVideoViewerScreen> {
  VideoPlayerController? _controller;

  String _fmt(Duration d) {
    final total = d.inSeconds < 0 ? 0 : d.inSeconds;
    final mm = (total ~/ 60).toString().padLeft(2, '0');
    final ss = (total % 60).toString().padLeft(2, '0');
    return '$mm:$ss';
  }

  @override
  void initState() {
    super.initState();
    final uri = Uri.tryParse(widget.url);
    if (uri != null) {
      _controller = VideoPlayerController.networkUrl(uri)
        ..initialize().then((_) {
          if (mounted) setState(() {});
        }).catchError((_) {});
      _controller?.addListener(() {
        if (mounted) setState(() {});
      });
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = _controller;
    final ready = c != null && c.value.isInitialized;
    final position = ready ? c.value.position : Duration.zero;
    final duration = ready ? c.value.duration : Duration.zero;
    final maxMs = duration.inMilliseconds <= 0 ? 1 : duration.inMilliseconds;
    final posMs = position.inMilliseconds.clamp(0, maxMs).toDouble();

    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        elevation: 0,
      ),
      body: ready
          ? SafeArea(
              child: Column(
                children: [
                  Expanded(
                    child: Center(
                      child: GestureDetector(
                        onTap: () async {
                          if (c.value.isPlaying) {
                            await c.pause();
                          } else {
                            await c.play();
                          }
                        },
                        child: AspectRatio(
                          aspectRatio: c.value.aspectRatio == 0 ? 16 / 9 : c.value.aspectRatio,
                          child: Stack(
                            alignment: Alignment.center,
                            children: [
                              VideoPlayer(c),
                              AnimatedOpacity(
                                duration: const Duration(milliseconds: 180),
                                opacity: c.value.isPlaying ? 0 : 1,
                                child: Container(
                                  width: 72,
                                  height: 72,
                                  decoration: BoxDecoration(
                                    color: Colors.black.withValues(alpha: 0.42),
                                    shape: BoxShape.circle,
                                  ),
                                  alignment: Alignment.center,
                                  child: const Icon(
                                    Icons.play_arrow_rounded,
                                    color: Colors.white,
                                    size: 46,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
                    child: Column(
                      children: [
                        Slider(
                          value: posMs,
                          min: 0,
                          max: maxMs.toDouble(),
                          onChanged: (v) async {
                            await c.seekTo(Duration(milliseconds: v.round()));
                          },
                        ),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 8),
                          child: Row(
                            children: [
                              Text(
                                _fmt(position),
                                style: const TextStyle(color: Colors.white70),
                              ),
                              const Spacer(),
                              Text(
                                _fmt(duration),
                                style: const TextStyle(color: Colors.white70),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            IconButton(
                              onPressed: () async {
                                final back = position - const Duration(seconds: 10);
                                await c.seekTo(back < Duration.zero ? Duration.zero : back);
                              },
                              icon: const Icon(
                                Icons.replay_10_rounded,
                                color: Colors.white,
                              ),
                            ),
                            const SizedBox(width: 12),
                            FilledButton(
                              onPressed: () async {
                                if (c.value.isPlaying) {
                                  await c.pause();
                                } else {
                                  await c.play();
                                }
                              },
                              child: Icon(
                                c.value.isPlaying
                                    ? Icons.pause_rounded
                                    : Icons.play_arrow_rounded,
                              ),
                            ),
                            const SizedBox(width: 12),
                            IconButton(
                              onPressed: () async {
                                final next = position + const Duration(seconds: 10);
                                await c.seekTo(next > duration ? duration : next);
                              },
                              icon: const Icon(
                                Icons.forward_10_rounded,
                                color: Colors.white,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            )
          : const Center(child: CircularProgressIndicator()),
    );
  }
}
