import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:video_player/video_player.dart';

import '../../common/media/image_viewer_screen.dart';
import '../../common/media/pdf_viewer_screen.dart';
import '../utils/chat_reply_codec.dart';
import 'chat_audio_bubble.dart';

class ChatMessageBubble extends StatelessWidget {
  const ChatMessageBubble({
    super.key,
    required this.contextForNavigation,
    required this.rawText,
    required this.mediaUrl,
    required this.isMine,
    required this.showName,
    required this.senderLabel,
    required this.timeLabel,
    required this.edited,
    required this.reaction,
    required this.forwarded,
    this.delivered = false,
    this.seen = false,
    required this.deleteState,
    this.voiceDurationSeconds,
    this.voiceUnread = false,
    this.onVoicePlayed,
    this.replySender,
    this.replySnippet,
    this.mediaMimeType,
    this.messageKind = 'TEXT',
    this.maxWidth = 380,
  });

  final BuildContext contextForNavigation;
  final String rawText;
  final String mediaUrl;
  final bool isMine;
  final bool showName;
  final String senderLabel;
  final String timeLabel;
  final bool edited;
  final String? reaction;
  final bool forwarded;
  final bool delivered;
  final bool seen;
  final String deleteState;
  final int? voiceDurationSeconds;
  final bool voiceUnread;
  final VoidCallback? onVoicePlayed;
  final String? replySender;
  final String? replySnippet;
  final String? mediaMimeType;
  final String messageKind;
  final double maxWidth;

  bool _isImageByUrl(String v) =>
      RegExp(r'\.(jpg|jpeg|png|webp|gif)$', caseSensitive: false).hasMatch(v);

  bool _isVoiceByUrl(String v) =>
      RegExp(r'\.(m4a|aac|mp3|wav)$', caseSensitive: false).hasMatch(v);

  bool _isVideoByUrl(String v) =>
      RegExp(r'\.(mp4|mov|m4v|webm)$', caseSensitive: false).hasMatch(v);

  bool _isImageByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'IMAGE' ||
        m.startsWith('image/') ||
        m.contains('jpeg') ||
        m.contains('jpg') ||
        m.contains('png') ||
        m.contains('webp') ||
        m.contains('gif');
  }

  bool _isVoiceByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'VOICE' ||
        m.startsWith('audio/') ||
        m.contains('mpeg') ||
        m.contains('mp4') ||
        m.contains('aac') ||
        m.contains('wav');
  }

  bool _isVideoByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'VIDEO' ||
        m.startsWith('video/') ||
        m.contains('mp4') ||
        m.contains('quicktime') ||
        m.contains('webm');
  }

  bool _isPdfByUrl(String v) =>
      RegExp(r'\.pdf$', caseSensitive: false).hasMatch(v);
  bool _shouldHideAutogeneratedMediaLabel({
    required String body,
    required String resolvedMediaUrl,
    required bool hasMedia,
    required String kind,
    String mime = '',
  }) {
    if (!hasMedia) return false;

    final normalizedBody = body.trim();
    if (normalizedBody.isEmpty) return true;

    final upperKind = kind.trim().toUpperCase();
    final lowerMime = mime.trim().toLowerCase();

    final parsed = Uri.tryParse(resolvedMediaUrl);
    final fileName =
        (parsed != null && parsed.pathSegments.isNotEmpty)
            ? Uri.decodeComponent(parsed.pathSegments.last.trim())
            : '';

    final stem = fileName.contains('.')
        ? fileName.substring(0, fileName.lastIndexOf('.'))
        : fileName;

    final candidates = <String>{
      fileName,
      fileName.replaceAll('_', ' '),
      stem,
      stem.replaceAll('_', ' '),
    }..removeWhere((e) => e.trim().isEmpty);

    if (candidates.any((e) => normalizedBody.toLowerCase() == e.toLowerCase())) {
      return true;
    }

    final looksLikeFileName = RegExp(
      r'^[^\/]+\.(jpg|jpeg|png|webp|gif|mp4|mov|m4v|webm|m4a|aac|mp3|wav|pdf|doc|docx|xls|xlsx|ppt|pptx)$',
      caseSensitive: false,
    ).hasMatch(normalizedBody);

    final isMediaish = upperKind == 'IMAGE' ||
        upperKind == 'VIDEO' ||
        upperKind == 'VOICE' ||
        upperKind == 'FILE' ||
        lowerMime.startsWith('image/') ||
        lowerMime.startsWith('video/') ||
        lowerMime.startsWith('audio/') ||
        lowerMime.contains('quicktime') ||
        lowerMime.contains('mp4') ||
        lowerMime.contains('webm') ||
        lowerMime.contains('mpeg') ||
        lowerMime.contains('aac') ||
        lowerMime.contains('wav') ||
        lowerMime.contains('pdf') ||
        lowerMime.contains('officedocument') ||
        lowerMime.contains('msword') ||
        lowerMime.contains('excel') ||
        lowerMime.contains('spreadsheet') ||
        lowerMime.contains('presentation');

    if (isMediaish && looksLikeFileName) {
      return true;
    }

    return false;
  }

  bool _forceHideMediaText({
    required String kind,
    required String mime,
    required String body,
    required bool hideAutogeneratedMediaLabel,
  }) {
    if (hideAutogeneratedMediaLabel) return true;

    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    final b = body.trim().toLowerCase();

    if (b.isEmpty) return true;
    if (b == '[image]' || b == '[video]' || b == '[voice]' || b == '[file]') {
      return true;
    }

    return k == 'IMAGE' ||
        k == 'VIDEO' ||
        k == 'VOICE' ||
        k == 'FILE' ||
        m.startsWith('image/') ||
        m.startsWith('video/') ||
        m.startsWith('audio/');
  }

  String _resolveMediaUrl(String raw) {
    final value = raw.trim();
    if (value.isEmpty) return '';
    final uri = Uri.tryParse(value);
    if (uri != null && uri.hasScheme) return value;

    const base = String.fromEnvironment('CM_API_BASE_URL');
    final normalizedBase = base.trim().replaceAll(RegExp(r'/+$'), '');
    if (normalizedBase.isEmpty) return value;

    final normalizedPath = value.startsWith('/') ? value : '/$value';
    return '$normalizedBase$normalizedPath';
  }

  String _displayFileName(String resolvedMediaUrl) {
    final parsed = Uri.tryParse(resolvedMediaUrl);
    if (parsed != null && parsed.pathSegments.isNotEmpty) {
      final last = Uri.decodeComponent(parsed.pathSegments.last.trim());
      if (last.isNotEmpty) return last;
    }
    final parts = resolvedMediaUrl.split('/');
    return parts.isEmpty ? 'File' : parts.last;
  }

  Widget _buildChecks() {
    if (!isMine) return const SizedBox.shrink();

    if (seen) {
      return Icon(
        Icons.done_all_rounded,
        size: 15,
        color: Colors.lightBlueAccent.shade100,
      );
    }

    if (delivered) {
      return Icon(
        Icons.done_all_rounded,
        size: 15,
        color: Colors.white.withValues(alpha: 0.72),
      );
    }

    return Icon(
      Icons.done_rounded,
      size: 15,
      color: Colors.white.withValues(alpha: 0.72),
    );
  }

  Future<void> _openAttachment(
    BuildContext context,
    String url,
    String label, {
    String kind = '',
    String mime = '',
  }) async {
    if (_isImageByUrl(url) || _isImageByMeta(kind, mime)) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => ImageViewerScreen(url: url, label: label),
        ),
      );
      return;
    }

    if (_isVideoByUrl(url) || _isVideoByMeta(kind, mime)) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => _InlineVideoViewerScreen(url: url),
        ),
      );
      return;
    }

    final lowerLabel = label.trim().toLowerCase();

    if (_isPdfByUrl(url) ||
        mime.trim().toLowerCase().contains('pdf') ||
        lowerLabel.endsWith('.pdf') ||
        lowerLabel == 'pdf' ||
        lowerLabel == 'pdf file') {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => PdfViewerScreen(url: url, label: label),
        ),
      );
      return;
    }

    final uri = Uri.tryParse(url);
    if (uri == null) return;

    await launchUrl(uri, mode: LaunchMode.platformDefault);
  }

  @override
  Widget build(BuildContext context) {
    final deleteMode = deleteState.trim().toUpperCase();
    final isDeletedForEveryone = deleteMode == 'DELETED_FOR_EVERYONE';
    final isDeletedForMe = deleteMode == 'DELETED_FOR_ME';

    final parts = splitReplyRaw(rawText);
    final inlineReplyPrefix = parts.replyPrefix.trim();
    final body = parts.bodyText.trim();

    var resolvedReplySender = (replySender ?? '').trim();
    var resolvedReplySnippet = (replySnippet ?? '').trim();

    if (resolvedReplySender.isEmpty && inlineReplyPrefix.startsWith('↪ ')) {
      final afterArrow = inlineReplyPrefix.substring(2).trim();
      final colon = afterArrow.indexOf(':');
      if (colon != -1) {
        resolvedReplySender = afterArrow.substring(0, colon).trim();
        resolvedReplySnippet = afterArrow.substring(colon + 1).trim();
      } else {
        resolvedReplySnippet = afterArrow;
      }
      if (resolvedReplySnippet.endsWith('—')) {
        resolvedReplySnippet = resolvedReplySnippet
            .substring(0, resolvedReplySnippet.length - 1)
            .trimRight();
      }
    }

    final lowerBody = body.toLowerCase();
    final resolvedMediaUrl = _resolveMediaUrl(mediaUrl);
    final lowerUrl = resolvedMediaUrl.toLowerCase();
    final hasMedia = resolvedMediaUrl.trim().isNotEmpty;
    final hideAutogeneratedMediaLabel = _shouldHideAutogeneratedMediaLabel(
      body: body,
      resolvedMediaUrl: resolvedMediaUrl,
      hasMedia: hasMedia,
      kind: messageKind,
      mime: (mediaMimeType ?? '').trim(),
    );

    final forceHideMediaText = _forceHideMediaText(
      kind: messageKind,
      mime: (mediaMimeType ?? '').trim(),
      body: body,
      hideAutogeneratedMediaLabel: hideAutogeneratedMediaLabel,
    );

    final isImage =
        hasMedia &&
        (_isImageByUrl(lowerUrl) ||
            _isImageByMeta(messageKind, (mediaMimeType ?? '').trim()));
    final isVoice =
        hasMedia &&
        (_isVoiceByUrl(lowerUrl) ||
            _isVoiceByMeta(messageKind, (mediaMimeType ?? '').trim()));
    final isPdf = hasMedia && _isPdfByUrl(lowerUrl);
    final isVideo =
        hasMedia &&
        (_isVideoByUrl(lowerUrl) ||
            _isVideoByMeta(messageKind, (mediaMimeType ?? '').trim()));
    final isFileLike = hasMedia && !isImage && !isVoice && !isVideo;
    final displayFileName = _displayFileName(resolvedMediaUrl);

    if (isDeletedForMe) {
      return const SizedBox.shrink();
    }

    return ConstrainedBox(
      constraints: BoxConstraints(maxWidth: maxWidth),
      child: Column(
        crossAxisAlignment: isMine
            ? CrossAxisAlignment.end
            : CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.fromLTRB(10, 7, 10, 6),
            decoration: BoxDecoration(
              color: isMine
                  ? const Color(0xFF0A84FF).withValues(alpha: 0.16)
                  : const Color(0xFF171B22).withValues(alpha: 0.94),
              borderRadius: BorderRadius.only(
                topLeft: const Radius.circular(16),
                topRight: const Radius.circular(16),
                bottomLeft: Radius.circular(isMine ? 16 : 5),
                bottomRight: Radius.circular(isMine ? 5 : 16),
              ),
              border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (showName && !isMine) ...[
                  Text(
                    senderLabel,
                    style: TextStyle(
                      color: Colors.white.withValues(alpha: 0.72),
                      fontSize: 11,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 4),
                ],
                if (forwarded) ...[
                  Container(
                    margin: const EdgeInsets.only(bottom: 6),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(
                          Icons.forward_rounded,
                          size: 13,
                          color: Colors.white.withValues(alpha: 0.68),
                        ),
                        const SizedBox(width: 4),
                        Text(
                          'Forwarded',
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.68),
                            fontSize: 11,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
                if (resolvedReplySender.isNotEmpty ||
                    resolvedReplySnippet.isNotEmpty ||
                    inlineReplyPrefix.isNotEmpty) ...[
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.fromLTRB(7, 5, 7, 5),
                    margin: const EdgeInsets.only(bottom: 6),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.08),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(
                        color: Colors.white.withValues(alpha: 0.05),
                      ),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          resolvedReplySender.isEmpty
                              ? 'Reply'
                              : resolvedReplySender,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.w700,
                            fontSize: 12,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          resolvedReplySnippet.isEmpty
                              ? 'Message'
                              : resolvedReplySnippet,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.72),
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
                if (isDeletedForEveryone) ...[
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        Icons.block_rounded,
                        size: 16,
                        color: Colors.white.withValues(alpha: 0.72),
                      ),
                      const SizedBox(width: 8),
                      Text(
                        'This message was deleted',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.72),
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    ],
                  ),
                ] else if (isImage) ...[
                  GestureDetector(
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      resolvedMediaUrl,
                      body.isEmpty ? 'Image' : body,
                      kind: messageKind,
                      mime: (mediaMimeType ?? '').trim(),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(16),
                      child: Image.network(
                        resolvedMediaUrl,
                        fit: BoxFit.cover,
                        errorBuilder: (context, error, stackTrace) => Container(
                          height: 180,
                          alignment: Alignment.center,
                          color: Colors.white.withValues(alpha: 0.06),
                          child: const Icon(
                            Icons.broken_image_outlined,
                            color: Colors.white70,
                          ),
                        ),
                      ),
                    ),
                  ),
                  if (body.isNotEmpty && !forceHideMediaText && !lowerBody.startsWith('[image]')) ...[
                    const SizedBox(height: 4),
                    Text(body, style: const TextStyle(color: Colors.white)),
                  ],
                ] else if (isVoice) ...[
                  ChatAudioBubble(
                    url: resolvedMediaUrl,
                    durationSeconds: voiceDurationSeconds,
                    isUnread: voiceUnread,
                    onPlayed: onVoicePlayed,
                  ),
                  if (body.isNotEmpty && !forceHideMediaText && !lowerBody.startsWith('[voice]')) ...[
                    const SizedBox(height: 4),
                    Text(body, style: const TextStyle(color: Colors.white)),
                  ],
                ] else if (isVideo) ...[
                  _InlineVideoBubble(
                    url: resolvedMediaUrl,
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      resolvedMediaUrl,
                      body.isEmpty ? 'Video' : body,
                      kind: messageKind,
                      mime: (mediaMimeType ?? '').trim(),
                    ),
                  ),
                  if (body.isNotEmpty && !forceHideMediaText) ...[
                    const SizedBox(height: 4),
                    Text(body, style: const TextStyle(color: Colors.white)),
                  ],
                ] else if (isPdf || isFileLike) ...[
                  GestureDetector(
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      resolvedMediaUrl,
                      body.isEmpty ? 'File' : body,
                      kind: messageKind,
                      mime: (mediaMimeType ?? '').trim(),
                    ),
                    child: Container(
                      width: double.infinity,
                      padding: const EdgeInsets.fromLTRB(12, 12, 12, 12),
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(
                          color: Colors.white.withValues(alpha: 0.05),
                        ),
                      ),
                      child: Row(
                        children: [
                          Container(
                            width: 34,
                            height: 34,
                            decoration: BoxDecoration(
                              color: Colors.white.withValues(alpha: 0.10),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            alignment: Alignment.center,
                            child: Icon(
                              isPdf
                                  ? Icons.picture_as_pdf_rounded
                                  : Icons.insert_drive_file_rounded,
                              color: Colors.white,
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              body.isNotEmpty && !hideAutogeneratedMediaLabel
                                  ? body
                                  : displayFileName,
                              maxLines: 2,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(color: Colors.white),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ] else if (body.isNotEmpty && !forceHideMediaText) ...[
                  Text(body, style: const TextStyle(color: Colors.white)),
                ],
                const SizedBox(height: 4),
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (edited)
                      Text(
                        'edited',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.55),
                          fontSize: 11,
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    if (edited) const SizedBox(width: 6),
                    Text(
                      timeLabel,
                      style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.62),
                        fontSize: 11,
                      ),
                    ),
                    if (isMine) const SizedBox(width: 6),
                    if (isMine) _buildChecks(),
                  ],
                ),
              ],
            ),
          ),
          if ((reaction ?? '').trim().isNotEmpty) ...[
            const SizedBox(height: 4),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(999),
                border: Border.all(color: Colors.white.withValues(alpha: 0.06)),
              ),
              child: Text(
                reaction!.trim(),
                style: const TextStyle(fontSize: 12),
              ),
            ),
          ],
        ],
      ),
    );
  }
}


class _InlineVideoBubble extends StatefulWidget {
  const _InlineVideoBubble({
    required this.url,
    required this.onTap,
  });

  final String url;
  final VoidCallback onTap;

  @override
  State<_InlineVideoBubble> createState() => _InlineVideoBubbleState();
}

class _InlineVideoBubbleState extends State<_InlineVideoBubble> {
  VideoPlayerController? _controller;

  @override
  void initState() {
    super.initState();
    final uri = Uri.tryParse(widget.url);
    if (uri != null) {
      _controller = VideoPlayerController.networkUrl(uri)
        ..initialize().then((_) {
          if (mounted) setState(() {});
        }).catchError((_) {});
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = _controller;
    final ready = c != null && c.value.isInitialized;

    return GestureDetector(
      onTap: widget.onTap,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: Container(
          constraints: const BoxConstraints(minHeight: 180, maxHeight: 260),
          width: double.infinity,
          color: Colors.white.withValues(alpha: 0.06),
          child: Stack(
            alignment: Alignment.center,
            children: [
              if (ready)
                AspectRatio(
                  aspectRatio: c.value.aspectRatio == 0
                      ? 16 / 9
                      : c.value.aspectRatio,
                  child: VideoPlayer(c),
                )
              else
                const SizedBox(
                  height: 180,
                  child: Center(
                    child: Icon(
                      Icons.videocam_rounded,
                      color: Colors.white70,
                      size: 40,
                    ),
                  ),
                ),
              Container(
                width: 52,
                height: 52,
                decoration: BoxDecoration(
                  color: Colors.black.withValues(alpha: 0.45),
                  shape: BoxShape.circle,
                ),
                alignment: Alignment.center,
                child: const Icon(
                  Icons.play_arrow_rounded,
                  color: Colors.white,
                  size: 32,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}


class _InlineVideoViewerScreen extends StatefulWidget {
  const _InlineVideoViewerScreen({
    required this.url,
  });

  final String url;

  @override
  State<_InlineVideoViewerScreen> createState() =>
      _InlineVideoViewerScreenState();
}

class _InlineVideoViewerScreenState extends State<_InlineVideoViewerScreen> {
  VideoPlayerController? _controller;

  String _fmt(Duration d) {
    final total = d.inSeconds < 0 ? 0 : d.inSeconds;
    final mm = (total ~/ 60).toString().padLeft(2, '0');
    final ss = (total % 60).toString().padLeft(2, '0');
    return '$mm:$ss';
  }

  @override
  void initState() {
    super.initState();
    final uri = Uri.tryParse(widget.url);
    if (uri != null) {
      _controller = VideoPlayerController.networkUrl(uri)
        ..initialize().then((_) {
          if (mounted) setState(() {});
        }).catchError((_) {});
      _controller?.addListener(() {
        if (mounted) setState(() {});
      });
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = _controller;
    final ready = c != null && c.value.isInitialized;
    final position = ready ? c.value.position : Duration.zero;
    final duration = ready ? c.value.duration : Duration.zero;
    final maxMs = duration.inMilliseconds <= 0 ? 1 : duration.inMilliseconds;
    final posMs = position.inMilliseconds.clamp(0, maxMs).toDouble();

    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        elevation: 0,
      ),
      body: ready
          ? SafeArea(
              child: Column(
                children: [
                  Expanded(
                    child: Center(
                      child: GestureDetector(
                        onTap: () async {
                          if (c.value.isPlaying) {
                            await c.pause();
                          } else {
                            await c.play();
                          }
                        },
                        child: AspectRatio(
                          aspectRatio: c.value.aspectRatio == 0
                              ? 16 / 9
                              : c.value.aspectRatio,
                          child: Stack(
                            alignment: Alignment.center,
                            children: [
                              VideoPlayer(c),
                              AnimatedOpacity(
                                duration: const Duration(milliseconds: 180),
                                opacity: c.value.isPlaying ? 0 : 1,
                                child: Container(
                                  width: 72,
                                  height: 72,
                                  decoration: BoxDecoration(
                                    color: Colors.black.withValues(alpha: 0.42),
                                    shape: BoxShape.circle,
                                  ),
                                  alignment: Alignment.center,
                                  child: const Icon(
                                    Icons.play_arrow_rounded,
                                    color: Colors.white,
                                    size: 46,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
                    child: Column(
                      children: [
                        Slider(
                          value: posMs,
                          min: 0,
                          max: maxMs.toDouble(),
                          onChanged: (v) async {
                            await c.seekTo(Duration(milliseconds: v.round()));
                          },
                        ),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 8),
                          child: Row(
                            children: [
                              Text(
                                _fmt(position),
                                style: const TextStyle(color: Colors.white70),
                              ),
                              const Spacer(),
                              Text(
                                _fmt(duration),
                                style: const TextStyle(color: Colors.white70),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            IconButton(
                              onPressed: () async {
                                final back = position - const Duration(seconds: 10);
                                await c.seekTo(back < Duration.zero ? Duration.zero : back);
                              },
                              icon: const Icon(Icons.replay_10_rounded, color: Colors.white),
                            ),
                            const SizedBox(width: 12),
                            FilledButton(
                              onPressed: () async {
                                if (c.value.isPlaying) {
                                  await c.pause();
                                } else {
                                  await c.play();
                                }
                              },
                              child: Icon(
                                c.value.isPlaying
                                    ? Icons.pause_rounded
                                    : Icons.play_arrow_rounded,
                              ),
                            ),
                            const SizedBox(width: 12),
                            IconButton(
                              onPressed: () async {
                                final next = position + const Duration(seconds: 10);
                                await c.seekTo(next > duration ? duration : next);
                              },
                              icon: const Icon(Icons.forward_10_rounded, color: Colors.white),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            )
          : const Center(child: CircularProgressIndicator()),
    );
  }
}
