import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../common/media/image_viewer_screen.dart';
import '../../common/media/pdf_viewer_screen.dart';
import '../utils/chat_reply_codec.dart';
import 'chat_audio_bubble.dart';

class ChatMessageBubble extends StatelessWidget {
  const ChatMessageBubble({
    super.key,
    required this.contextForNavigation,
    required this.rawText,
    required this.mediaUrl,
    required this.isMine,
    required this.showName,
    required this.senderLabel,
    required this.timeLabel,
    required this.edited,
    required this.reaction,
    required this.forwarded,
    this.delivered = false,
    this.seen = false,
    required this.deleteState,
    this.voiceDurationSeconds,
    this.voiceUnread = false,
    this.onVoicePlayed,
    this.replySender,
    this.replySnippet,
    this.mediaMimeType,
    this.messageKind = 'TEXT',
    this.maxWidth = 380,
  });

  final BuildContext contextForNavigation;
  final String rawText;
  final String mediaUrl;
  final bool isMine;
  final bool showName;
  final String senderLabel;
  final String timeLabel;
  final bool edited;
  final String? reaction;
  final bool forwarded;
  final bool delivered;
  final bool seen;
  final String deleteState;
  final int? voiceDurationSeconds;
  final bool voiceUnread;
  final VoidCallback? onVoicePlayed;
  final String? replySender;
  final String? replySnippet;
  final String? mediaMimeType;
  final String messageKind;
  final double maxWidth;

  bool _isImageByUrl(String v) =>
      RegExp(r'\.(jpg|jpeg|png|webp|gif)$', caseSensitive: false).hasMatch(v);

  bool _isVoiceByUrl(String v) =>
      RegExp(r'\.(m4a|aac|mp3|wav)$', caseSensitive: false).hasMatch(v);

  bool _isVoiceByMeta(String kind, String mime) {
    final k = kind.trim().toUpperCase();
    final m = mime.trim().toLowerCase();
    return k == 'VOICE' ||
        m.startsWith('audio/') ||
        m.contains('mpeg') ||
        m.contains('mp4') ||
        m.contains('aac') ||
        m.contains('wav');
  }

  bool _isPdfByUrl(String v) =>
      RegExp(r'\.pdf$', caseSensitive: false).hasMatch(v);


  bool _shouldHideAutogeneratedMediaLabel({
    required String body,
    required String resolvedMediaUrl,
    required bool hasMedia,
    required String kind,
  }) {
    if (!hasMedia) return false;

    final upperKind = kind.trim().toUpperCase();
    if (upperKind == 'IMAGE' ||
        upperKind == 'VIDEO' ||
        upperKind == 'VOICE' ||
        upperKind == 'FILE') {
      return true;
    }

    final normalizedBody = body.trim();
    if (normalizedBody.isEmpty) return true;

    final parsed = Uri.tryParse(resolvedMediaUrl);
    final fileName =
        (parsed != null && parsed.pathSegments.isNotEmpty)
            ? Uri.decodeComponent(parsed.pathSegments.last.trim())
            : '';

    if (fileName.isEmpty) return false;

    return normalizedBody == fileName ||
        normalizedBody == fileName.replaceAll('_', ' ');
  }

  String _resolveMediaUrl(String raw) {
    final value = raw.trim();
    if (value.isEmpty) return '';
    final uri = Uri.tryParse(value);
    if (uri != null && uri.hasScheme) return value;

    const base = String.fromEnvironment('CM_API_BASE_URL');
    final normalizedBase = base.trim().replaceAll(RegExp(r'/+$'), '');
    if (normalizedBase.isEmpty) return value;

    final normalizedPath = value.startsWith('/') ? value : '/$value';
    return '$normalizedBase$normalizedPath';
  }

  Widget _buildChecks() {
    if (!isMine) return const SizedBox.shrink();

    if (seen) {
      return Icon(
        Icons.done_all_rounded,
        size: 15,
        color: Colors.lightBlueAccent.shade100,
      );
    }

    if (delivered) {
      return Icon(
        Icons.done_all_rounded,
        size: 15,
        color: Colors.white.withValues(alpha: 0.72),
      );
    }

    return Icon(
      Icons.done_rounded,
      size: 15,
      color: Colors.white.withValues(alpha: 0.72),
    );
  }

  Future<void> _openAttachment(
    BuildContext context,
    String url,
    String label,
  ) async {
    if (_isImageByUrl(url)) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => ImageViewerScreen(url: url, label: label),
        ),
      );
      return;
    }

    if (_isPdfByUrl(url)) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => PdfViewerScreen(url: url, label: label),
        ),
      );
      return;
    }

    final uri = Uri.tryParse(url);
    if (uri == null) {
      return;
    }
    await launchUrl(uri, mode: LaunchMode.externalApplication);
  }

  @override
  Widget build(BuildContext context) {
    final deleteMode = deleteState.trim().toUpperCase();
    final isDeletedForEveryone = deleteMode == 'DELETED_FOR_EVERYONE';
    final isDeletedForMe = deleteMode == 'DELETED_FOR_ME';

    final parts = splitReplyRaw(rawText);
    final inlineReplyPrefix = parts.replyPrefix.trim();
    final body = parts.bodyText.trim();

    var resolvedReplySender = (replySender ?? '').trim();
    var resolvedReplySnippet = (replySnippet ?? '').trim();

    if (resolvedReplySender.isEmpty && inlineReplyPrefix.startsWith('↪ ')) {
      final afterArrow = inlineReplyPrefix.substring(2).trim();
      final colon = afterArrow.indexOf(':');
      if (colon != -1) {
        resolvedReplySender = afterArrow.substring(0, colon).trim();
        resolvedReplySnippet = afterArrow.substring(colon + 1).trim();
      } else {
        resolvedReplySnippet = afterArrow;
      }
      if (resolvedReplySnippet.endsWith('—')) {
        resolvedReplySnippet = resolvedReplySnippet
            .substring(0, resolvedReplySnippet.length - 1)
            .trimRight();
      }
    }

    final lowerBody = body.toLowerCase();
    final resolvedMediaUrl = _resolveMediaUrl(mediaUrl);
    final lowerUrl = resolvedMediaUrl.toLowerCase();
    final hasMedia = resolvedMediaUrl.trim().isNotEmpty;
    final hideAutogeneratedMediaLabel = _shouldHideAutogeneratedMediaLabel(
      body: body,
      resolvedMediaUrl: resolvedMediaUrl,
      hasMedia: hasMedia,
      kind: messageKind,
    );

    final isImage = hasMedia && _isImageByUrl(lowerUrl);
    final isVoice =
        hasMedia &&
        (_isVoiceByUrl(lowerUrl) ||
            _isVoiceByMeta(messageKind, (mediaMimeType ?? '').trim()));
    final isPdf = hasMedia && _isPdfByUrl(lowerUrl);
    final isFileLike = hasMedia && !isImage && !isVoice;

    if (isDeletedForMe) {
      return const SizedBox.shrink();
    }

    return ConstrainedBox(
      constraints: BoxConstraints(maxWidth: maxWidth),
      child: Column(
        crossAxisAlignment: isMine
            ? CrossAxisAlignment.end
            : CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.fromLTRB(10, 7, 10, 6),
            decoration: BoxDecoration(
              color: isMine
                  ? const Color(0xFF0A84FF).withValues(alpha: 0.16)
                  : const Color(0xFF171B22).withValues(alpha: 0.94),
              borderRadius: BorderRadius.only(
                topLeft: const Radius.circular(16),
                topRight: const Radius.circular(16),
                bottomLeft: Radius.circular(isMine ? 16 : 5),
                bottomRight: Radius.circular(isMine ? 5 : 16),
              ),
              border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (showName && !isMine) ...[
                  Text(
                    senderLabel,
                    style: TextStyle(
                      color: Colors.white.withValues(alpha: 0.72),
                      fontSize: 11,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 4),
                ],
                if (forwarded) ...[
                  Container(
                    margin: const EdgeInsets.only(bottom: 6),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(
                          Icons.forward_rounded,
                          size: 13,
                          color: Colors.white.withValues(alpha: 0.68),
                        ),
                        const SizedBox(width: 4),
                        Text(
                          'Forwarded',
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.68),
                            fontSize: 11,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
                if (resolvedReplySender.isNotEmpty ||
                    resolvedReplySnippet.isNotEmpty ||
                    inlineReplyPrefix.isNotEmpty) ...[
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.fromLTRB(7, 5, 7, 5),
                    margin: const EdgeInsets.only(bottom: 6),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.08),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(
                        color: Colors.white.withValues(alpha: 0.05),
                      ),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          resolvedReplySender.isEmpty
                              ? 'Reply'
                              : resolvedReplySender,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.w700,
                            fontSize: 12,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          resolvedReplySnippet.isEmpty
                              ? 'Message'
                              : resolvedReplySnippet,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.72),
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
                if (isDeletedForEveryone) ...[
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        Icons.block_rounded,
                        size: 16,
                        color: Colors.white.withValues(alpha: 0.72),
                      ),
                      const SizedBox(width: 8),
                      Text(
                        'This message was deleted',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.72),
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    ],
                  ),
                ] else if (isImage) ...[
                  GestureDetector(
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      mediaUrl,
                      body.isEmpty ? 'Image' : body,
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(16),
                      child: Image.network(
                        mediaUrl,
                        fit: BoxFit.cover,
                        errorBuilder: (context, error, stackTrace) => Container(
                          height: 180,
                          alignment: Alignment.center,
                          color: Colors.white.withValues(alpha: 0.06),
                          child: const Icon(
                            Icons.broken_image_outlined,
                            color: Colors.white70,
                          ),
                        ),
                      ),
                    ),
                  ),
                  if (body.isNotEmpty && !hideAutogeneratedMediaLabel && !lowerBody.startsWith('[image]')) ...[
                    const SizedBox(height: 4),
                    Text(body, style: const TextStyle(color: Colors.white)),
                  ],
                ] else if (isVoice) ...[
                  ChatAudioBubble(
                    url: resolvedMediaUrl,
                    durationSeconds: voiceDurationSeconds,
                    isUnread: voiceUnread,
                    onPlayed: onVoicePlayed,
                  ),
                  if (body.isNotEmpty && !hideAutogeneratedMediaLabel && !lowerBody.startsWith('[voice]')) ...[
                    const SizedBox(height: 4),
                    Text(body, style: const TextStyle(color: Colors.white)),
                  ],
                ] else if (isPdf || isFileLike) ...[
                  GestureDetector(
                    onTap: () => _openAttachment(
                      contextForNavigation,
                      mediaUrl,
                      body.isEmpty ? 'File' : body,
                    ),
                    child: Container(
                      width: double.infinity,
                      padding: const EdgeInsets.fromLTRB(12, 12, 12, 12),
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(
                          color: Colors.white.withValues(alpha: 0.05),
                        ),
                      ),
                      child: Row(
                        children: [
                          Container(
                            width: 34,
                            height: 34,
                            decoration: BoxDecoration(
                              color: Colors.white.withValues(alpha: 0.10),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            alignment: Alignment.center,
                            child: Icon(
                              isPdf
                                  ? Icons.picture_as_pdf_rounded
                                  : Icons.insert_drive_file_rounded,
                              color: Colors.white,
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              body.isEmpty ? mediaUrl.split('/').last : body,
                              maxLines: 2,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(color: Colors.white),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ] else if (body.isNotEmpty && !hideAutogeneratedMediaLabel) ...[
                  Text(body, style: const TextStyle(color: Colors.white)),
                ],
                const SizedBox(height: 4),
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (edited)
                      Text(
                        'edited',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.55),
                          fontSize: 11,
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    if (edited) const SizedBox(width: 6),
                    Text(
                      timeLabel,
                      style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.62),
                        fontSize: 11,
                      ),
                    ),
                    if (isMine) const SizedBox(width: 6),
                    if (isMine) _buildChecks(),
                  ],
                ),
              ],
            ),
          ),
          if ((reaction ?? '').trim().isNotEmpty) ...[
            const SizedBox(height: 4),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(999),
                border: Border.all(color: Colors.white.withValues(alpha: 0.06)),
              ),
              child: Text(
                reaction!.trim(),
                style: const TextStyle(fontSize: 12),
              ),
            ),
          ],
        ],
      ),
    );
  }
}
