// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgz_EoNO-hnf6udoeaTsGMl_ilriTemo',
    appId: '1:682658545733:web:53fc70594257a5ae1aa32c',
    messagingSenderId: '682658545733',
    projectId: 'classmate-f17d6',
    authDomain: 'classmate-f17d6.firebaseapp.com',
    storageBucket: 'classmate-f17d6.firebasestorage.app',
    measurementId: 'G-LRVL33319H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0NrjJSW6t6c0Nnd6DzwZArAqabvdvkL4',
    appId: '1:682658545733:android:2ce716747ff621c41aa32c',
    messagingSenderId: '682658545733',
    projectId: 'classmate-f17d6',
    storageBucket: 'classmate-f17d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvkvqAXdYwn35o-oqcm7meQGzLs4qYhs',
    appId: '1:682658545733:ios:4b80bea6f8a583281aa32c',
    messagingSenderId: '682658545733',
    projectId: 'classmate-f17d6',
    storageBucket: 'classmate-f17d6.firebasestorage.app',
    iosBundleId: 'com.tonyaboud.classmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKvkvqAXdYwn35o-oqcm7meQGzLs4qYhs',
    appId: '1:682658545733:ios:c3a77da519a4e3831aa32c',
    messagingSenderId: '682658545733',
    projectId: 'classmate-f17d6',
    storageBucket: 'classmate-f17d6.firebasestorage.app',
    iosBundleId: 'com.example.classmateMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSgz_EoNO-hnf6udoeaTsGMl_ilriTemo',
    appId: '1:682658545733:web:c0148c1c4a3e35771aa32c',
    messagingSenderId: '682658545733',
    projectId: 'classmate-f17d6',
    authDomain: 'classmate-f17d6.firebaseapp.com',
    storageBucket: 'classmate-f17d6.firebasestorage.app',
    measurementId: 'G-3YN34B73HM',
  );
}
